# Generated by Django 3.2 on 2025-09-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('season', models.CharField(choices=[('spring', 'Spring Festival'), ('summer', 'Summer Collection'), ('monsoon', 'Monsoon Special'), ('autumn', 'Autumn Fashion'), ('winter', 'Winter Collection'), ('onam', 'Onam Festival'), ('vishu', 'Vishu Celebration'), ('wedding', 'Wedding Season'), ('diwali', 'Diwali Collection'), ('pongal', 'Pongal Festival')], max_length=20)),
                ('style', models.CharField(choices=[('kerala_traditional', 'Kerala Traditional'), ('kerala_modern', 'Kerala Modern Fusion'), ('kerala_bridal', 'Kerala Bridal'), ('south_indian', 'South Indian'), ('north_indian', 'North Indian'), ('indo_western', 'Indo Western')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/seasonal/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL', null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Seasonal Galleries',
                'ordering': ['-start_date', 'title'],
            },
        ),
    ]
